stages:
  - build
  - test

build website:
  stage: build
  image: node
  script:
    - cd static-website
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./static-website/public

test artifact:
  stage: test
  script:
    - grep "Gatsby" ./static-website/public/index.html
    - grep "XXXXXXXXX" ./static-website/public/index.html