stages:
  - build
  - test

build website:
  stage: build
  image: node
  script:
    - cd static-website
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./static-website/public

test artifact:
  stage: test
  image: alpine
  script:
    - grep -q "Gatsby" ./static-website/public/index.html

test website:
  stage: test
  image: node
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"